system:
  version : '2.0.2'
foods:
  data_version : 4
site:
  url: 'http://www.pockettoushituryou.com/'
  name : 'ポケット糖質量'
  title : 'ポケット糖質量'
  description: 'ポケット糖質量は1200種類以上の食品に含まれる糖質量が検索できるサイトです。
                100グラムあたりの糖質量と、それぞれの食品の1回分を目安とした分量に含まれるエネルギー（カロリー）・たんぱく質・脂質・塩分が表示できます。
                健康づくりのためにぜひご利用ください。'
  og:
    type: 'website'
    title : 'ポケット糖質量　糖質制限中に糖質量を一発検索・一覧表示'
